In [1170]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [1171]:
stroke = pd.read_csv('healthcare-dataset-stroke-data.csv')
stroke.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1

In [1172]:
stroke[('stroke')].value_counts()

0    4861
1     249
Name: stroke, dtype: int64

In [1173]:
shuffled_data = stroke.sample(frac=1,random_state=4)
stroke_df = stroke.loc[stroke['stroke'] == 1]
non_stroke_df = stroke.loc[stroke['stroke'] == 0].sample(n= 100,random_state= 101)

In [1174]:
normalized_stroke = pd.concat([stroke_df, non_stroke_df])

In [1175]:
def input_bmi(cols):
    bmi = cols[0]
    stroke = cols [1]
   
    
    if pd.isnull(bmi):
        return 28.6
    else:
        return bmi

In [1176]:
normalized_stroke['bmi'] = stroke[['bmi', 'stroke']].apply(input_bmi, axis=1)

In [1177]:
#residence = pd.get_dummies(normalized_stroke['Residence_type'])
#residence.head()

In [1178]:
residence = pd.get_dummies(normalized_stroke["Residence_type"], drop_first= True)
normalized_stroke.drop(["Residence_type"], axis = 1, inplace = True)
normalized_stroke = pd.concat([normalized_stroke, residence], axis = 1)
normalized_stroke.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,avg_glucose_level,bmi,smoking_status,stroke,Urban
0,9046,Male,67.0,0,1,Yes,Private,228.69,36.6,formerly smoked,1,1
1,51676,Female,61.0,0,0,Yes,Self-employed,202.21,28.6,never smoked,1,0
2,31112,Male,80.0,0,1,Yes,Private,105.92,32.5,never smoked,1,0
3,60182,Female,49.0,0,0,Yes,Private,171.23,34.4,smokes,1,1
4,1665,Female,79.0,1,0,Yes,Self-employed,174.12,24.0,never smoked,1,0

In [1179]:
#normalized_stroke.rename(columns={'Urban':'Residence_type'}, 
                 #inplace=True)

In [1180]:
sex = pd.get_dummies(normalized_stroke['gender'])
sex = pd.get_dummies(normalized_stroke["gender"], drop_first= True)
normalized_stroke.drop(["gender"], axis = 1, inplace = True)
normalized_stroke = pd.concat([normalized_stroke, sex], axis = 1)

In [1181]:
#marital_status = pd.get_dummies(normalized_stroke['ever_married'])

In [1182]:
#marital_status = pd.get_dummies(normalized_stroke["ever_married"], drop_first= True)

In [1183]:
normalized_stroke.drop(["ever_married", "smoking_status"], axis = 1, inplace = True)

In [1184]:
normalized_stroke = pd.concat([normalized_stroke, marital_status], axis = 1)

In [1185]:
normalized_stroke.rename(columns={'Yes':'marital_status'}, 
                 inplace=True)

In [1186]:
occupation = pd.get_dummies(normalized_stroke['work_type'])

In [1187]:
normalized_stroke.drop(["work_type"], axis = 1, inplace = True)

In [1188]:
#normalized_stroke = pd.concat([normalized_stroke, occupation], axis = 1)

In [1189]:
#normalized_stroke.drop(["avg_glucose_level"], axis = 1, inplace = True)

In [1190]:
normalized_stroke.head()

,id,age,hypertension,heart_disease,avg_glucose_level,bmi,stroke,Urban,Male,marital_status
0,9046,67.0,0,1,228.69,36.6,1,1,1,1
1,51676,61.0,0,0,202.21,28.6,1,0,0,1
2,31112,80.0,0,1,105.92,32.5,1,0,1,1
3,60182,49.0,0,0,171.23,34.4,1,1,0,1
4,1665,79.0,1,0,174.12,24.0,1,0,0,1

In [1191]:
normalized_stroke.drop(["id"], axis = 1, inplace = True)

In [1192]:
X = normalized_stroke

In [1193]:
y = normalized_stroke['stroke']

y.head()

0    1
1    1
2    1
3    1
4    1
Name: stroke, dtype: int64

In [1194]:
from sklearn.model_selection import train_test_split

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5)

In [1195]:
# Import the AdaBoost classifier
from sklearn.ensemble import AdaBoostClassifier


# Create adaboost classifer object
abc = AdaBoostClassifier(n_estimators=200, learning_rate=0.5, random_state=0)

# Train Adaboost Classifer
model1 = abc.fit(X_train, y_train)


#Predict the response for test dataset
y_pred = model1.predict(X_test)

In [1196]:
from sklearn.metrics import accuracy_score


# calculate and print model accuracy
print("AdaBoost Classifier Model Accuracy:", accuracy_score(y_test, y_pred))

AdaBoost Classifier Model Accuracy: 1.0

In [1197]:
from sklearn.ensemble import AdaBoostClassifier


# import Support Vector Classifier
from sklearn.svm import SVC


# import scikit-learn metrics module for accuracy calculation
from sklearn.metrics import accuracy_score
svc=SVC(probability=True, kernel='linear')


# create adaboost classifer object
abc =AdaBoostClassifier(n_estimators=50, base_estimator=svc,learning_rate=1, random_state=0)


# train adaboost classifer
model2 = abc.fit(X_train, y_train)


# predict the response for test dataset
y_pred = model2.predict(X_test)


# calculate and print model accuracy
print("Model Accuracy with SVC Base Estimator:",accuracy_score(y_test, y_pred))

Model Accuracy with SVC Base Estimator: 0.9885714285714285